sudo: required

dist: xenial
language: c

branches:
  only:
    - master

services:
 - docker

before_install:
 - pip install --user --upgrade awscli
 - ./base.bash

script:
 - ./build.bash --make-packages
 - ./build_example.bash

after_success:
 - ./publish.sh llvm-obfuscator-arm-x86.txz

env:
  global:
    # Secure keys below are encrypted with travis encrypt gem
    # Example encryption: travis encrypt AWS_SECRET_ACCESS_KEY=foo
    # See https://docs.travis-ci.com/user/encryption-keys/
    # AWS_ACCESS_KEY_ID
    - secure: "c6DtuP/y6lcJDhwjpLk/d3T9Oo1Fy9EW9mr0OsBQSq/5ctJsFtRxRsHVr2HtSD41Hd4de7xZoxGrk7kSDtrGxT7uRQwLREzaPRf0Vq/hjWcsfs/4vg6M5zhYrAYUSA28V7r7c2qmRiMLrHxnnzem56wwQG9Cn9kLSUg5Vx0kE4XayEdWKHlps9CP0d6ytgjqmUe0yBV9qJMGkMH/lp+LyK7HWo79iUrWBar+nTBxEeiEVFQqOOESB+LXBawx97L5+NWDL0IVvhkr78FU8XM/lV6gddulw5yOuruJ6bjznRaA6AbPx1dxf8o0ptP8QwgFsVQ/hlXc9cOwtRkobiktsVnDVtm2kuZwwUgRUa8i0A8PzG6w2SxR78UGBVxygDfrUQcQJ/zGIyqEehIi3drx9qEKMwjDoM2OS0b962Bld1Ex9glJdBbtO+TKFuYYU8/wEzzAF3IGMLC2CJ/L7r7IFcs6Y61KbicdUq1AY+Fx2RUpKJoZmQfknpi6IvZd1/1O5w5kqiAoKScqaAfZ5f84MBS6/CtLArFzWxWCliorBL9tW7NNGqtQ5kR+tBZ9/BLnvuNoMOnXlWJOhY9e4nCQeCAGG2AQ5LgcMGqrIcOiAEXHxg0fhuveygHkCd6Qjz5iJKIjrBokbwXZ2cms4ocLSxuJ2olNZXd0RgWKLrjrDhk="
    # AWS_SECRET_ACCESS_KEY
    - secure: "I025brJmSPMRp2oAvEYRB/xzqhVNYFJRoQnV8CjdV8uHYXOquHZGFyzLOCT1lRRGJ81geqa5uhWJ6e36sKd9kgk4IXW+DH5aPpOzv2B8p8dJKITIjUP7OpnIRghCsnb8JMFWqZUZ3YhmYShQY/eVByNneAyGLIYh6gsQyfqvoodf0t6ExlgNBLvJPWYfOz+dwpx+zE2HRim1+RRfdOYVMsvTmu5rrHTHn1fWqCbQCjarpvphNFTlgKU2mhxOhcSo4HR8xsYE6GbLc+ysufRLAqTOTMMPg9THiOdJqc1ZtXEvaw0StUeTEbIJlQSAV/lydRvQb1npJHFffoWy1ZdZEIjuX5ZkQkDvh/8TR6AJtGd4QUH3hEKsA5LhUrxgSZRCUMW5JyqWyiu7wC2Q9n2kpKUaDQKL6YfzKpzRa7txCf6YTIoUbzI9797UJUO6fgGgOQJzYhOUsFV23YyOsLete1bRuQkRKl3tmlv+KuoUlxxVtaO2kMWh33CHeE9z986pf1jsiMoHzk1D+tnGtL4lotFK2gQv7Ws9XlsBog0fNuh80kZ4P/hVQAM9TShesR+ebAPLckr334V8zjEdkiyz251fATYL5V7DY2iAZMA187ynz1HgZEopob0Gkz0kcrVI3JAvM8sxmXAEBDmoqysm3gAOQoFDgmjgdQtJW/1RrUE="
    # GITHUB_TOKEN
    - secure: "XnCmNEVc2qh1nvKNhEn4/yaeQNWGlAGH/7lSaKjK3LoJDeP4w1rCPs9jghpPes+9rUNEh4e3ekmKGUGIqJwRuzQPWM+zHza4WK4oXs43rd2hyfhRb2y+niLpTNc+RuiGtLobyc3IX3HaUeN6Bf9x9R49/3jxY/+lgYKhQ29Pw25CumQvQQjq6SYRyhndnrXeLQ4LWzSYEPpwYSQ5F7VEDs7FN3tX0IvfJlN+SiP+f8DHdMqoyPOBnDdEodt/erMcO7gm9inhZ6hWvGSJwi5nLd+SI2qlHFgRAFRugPe0kk2FBiBHpGYBPE7cJzKStJrQGQz7dVGgHwcgJrp5T9//HZtp2LH5iGNue+mdDeMtX5zShY+UhvXEX5/nnREHFz/9IFvz57MHqrEjjyxufOVHBnJM/5NVroKxgwUyxojSQZYxNKqzs046nVPHn5QWaseoeC1vxZ6XfxeMjv1Y/9L7OJfFgf4EFukhS/oPv/szrKBiKeBWTq36yQa2Fi+K/UNsE/IzD3RxftOSqz2Nev6fjl/t+keSFtJH/GWskmaKD+vuMkFSKeg8SXE+yZspkkFzAImCiQI5vWJhzzQK/qjoLonvrtwXObqXQU3JY7LfRZzNgNGXebWegw0DLFkAvoV8FxLCHhC+50eK5bob8UM0z7I02cibacim7iKmaP0G4W8="
